name: Generate and Deploy Static Nuxtjs Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate dist

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install deps
        run: npm ci

      - name: Lint then fix
        run: npm run lint:fix

      - name: Nuxt generate
        run: npm run generate

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy static page
    environment: hostinger-deployment

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy using rsync over SSH key
        env:
          user: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          target_dir: ${{ secrets.TARGET_DIRECTORY }}
        run: |
          rsync -avz --delete \
            --exclude='.htaccess' \
            -e "ssh -i ~/.ssh/id_rsa -p $port -o StrictHostKeyChecking=no" \
            dist/ $user@$host:$target_dir
